[package]
name = "fyrox-ui"
version = "0.17.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2021"
license = "MIT"
description = "Extendable UI library"
keywords = ["ui", "game", "gui"]
categories = ["game-development", "gui"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
homepage = "https://rg3d.rs"
documentation = "https://docs.rs/fyrox-ui"
repository = "https://github.com/FyroxEngine/Fyrox"
readme = "README.md"
resolver = "2"
rust-version = "1.56"

[dependencies]
fyrox-core = { path = "../fyrox-core", version = "0.20.0" }
lazy_static = "1.4.0"
copypasta = "0.8.1"
fontdue = "0.7.2"
notify = "4.0"
fxhash = "0.2.1"
strum = "0.24.0"
strum_macros = "0.24.0"

[features]
enable_profiler = ["fyrox-core/enable_profiler"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sysinfo = "0.20.0"
